name: build-artifact

env:
  AUTO_PR_GH_PAT: ${{ secrets.AUTO_PR_GH_PAT }}

  FAILED_WORKFLOW_ISSUE_CREATION_REPO_NAME:     ArmyEITaaS/Issues
  FAILED_WORKFLOW_ISSUE_CREATION_WORKFLOW_NAME: issue-creation-workflow-failed

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *' # Once a month on the 1st of each month, keep artifact from expiring
  workflow_dispatch:

jobs:
  build-artifact:
    name:    Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.2.2

      # Using rsync to easily copy VDOT files while excluding hidden .git/.github files
      - name: Copy Files for Artifact
        run:  rsync -av --exclude=".*" "${{ github.workspace }}" ./artifact

      - name: Upload as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name:              virtual-desktop-optimization-tool
          path:              "${{ github.workspace }}/artifact"
          if-no-files-found: error


  create-issue-on-failure:
    name:    Create Issue on Failure
    if:      contains(fromJSON('["push", "schedule", "workflow_dispatch"]'), github.event_name) && failure()
    needs:   [build-artifact] # Add all workflow jobs to needs to alert on failure.
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue for Failed Workflow
        uses: ArmyEITaaS/workflow-dispatch@v1
        with:
          token:    ${{ env.AUTO_PR_GH_PAT }}
          repo:     ${{ env.FAILED_WORKFLOW_ISSUE_CREATION_REPO_NAME }}
          ref:      main
          workflow: ${{ env.FAILED_WORKFLOW_ISSUE_CREATION_WORKFLOW_NAME }}
          inputs:   '{"FAILED_WORKFLOW_NAME":"${{ github.workflow }}","FAILED_WORKFLOW_REPO_NAME":"${{ github.repository }}","FAILED_WORKFLOW_RUN_ID":"${{ github.run_id }}","ISSUE_TITLE_PREFIX":"${{ github.workflow }} Workflow Failed"}'
